GET http://localhost:5000/values/

###

GET http://localhost:5000/values/1

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username" : "roy",
    "password" : "password"
}

###

POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username" : "nam3@gmail.com",
    "password" : "29041997"
}

###

GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI0IiwidW5pcXVlX25hbWUiOiJyb3kiLCJuYmYiOjE1NzM2MjM2NjIsImV4cCI6MTU3MzcxMDA2MiwiaWF0IjoxNTczNjIzNjYyfQ.HR-DqQ1wt1gTQL5RvioadwyEHsjNwCOVJoVkNiACNR5Hl-WeUeYlFrRmdZOHvvhNNenTtzITucRan5gn-vxGQw

###
GET http://localhost:5000/users/1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI0IiwidW5pcXVlX25hbWUiOiJyb3kiLCJuYmYiOjE1NzM2MjM2NjIsImV4cCI6MTU3MzcxMDA2MiwiaWF0IjoxNTczNjIzNjYyfQ.HR-DqQ1wt1gTQL5RvioadwyEHsjNwCOVJoVkNiACNR5Hl-WeUeYlFrRmdZOHvvhNNenTtzITucRan5gn-vxGQw

